version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - mynetwork

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      # Se sua aplicação ou scripts Python puderem usar essa variável para configurar o endpoint do Ollama:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - mynetwork

volumes:
  ollama:

networks:
  mynetwork:
